# This workflow will build and push a new Docker image to the default Artifact Registry in SSB.
#
# Overview:
# 1. Authenticate to Google Cloud
# 2. Authenticate to Artifact Registry
# 3. Build and publish a docker image to Google Artifact Registry
# 
# To configure this workflow:
# 1. Change the values for the IMAGE_NAME, TEAM_NAME and TAG environment variables (below).
# 
# This workflow is tailored for SSB´s setup, however if you wish to use this in a non SSB context ensure/change the following:
# 1. Create GitHub secrets for GAR_PROJECT_NUMBER and GAR_PROJECT_ID (Number and ID for the Artifact Registry project).
# 2. Create and configure Workload Identity Federation for GitHub.

name: Docker Image CI

on:
  push:
    branches: [ $default-branch ]

env:
  IMAGE_NAME:   # TODO: set this to your preferred image name
  TEAM_NAME:    # TODO: set this to you teams name
  TAG:          # TODO: set the preffered tag the image should have

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v1.1.1"
      with:
        # If you need to authenticate through another method, change the following variables:
        token_format: "access_token"        
        workload_identity_provider: "projects/${{ secrets.GAR_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/gh-actions/providers/gh-actions"
        service_account: "gh-actions-${{ env.TEAM_NAME }}@${{ secrets.GAR_PROJECT_ID }}.iam.gserviceaccount.com"
    - name: Login to registry
      uses: docker/login-action@v3
      with:
        # If you wish to push the image to another registry, change the following variable:
        registry: "europe-north1-docker.pkg.dev/${{ secrets.GAR_PROJECT_ID }}/${{ env.TEAM_NAME }}-docker"
        username: "oauth2accesstoken"
        password: "${{ steps.auth.outputs.access_token }}"

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push '${{ env.IMAGE_NAME }}'
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        # If you wish to push the image to another registry, change the following variable:
        tags: europe-north1-docker.pkg.dev/${{ secrets.GAR_PROJECT_ID }}/${{ env.TEAM_NAME }}-docker/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
